name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: laurajala
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Create dist folder if not exists
        run: mkdir -p dist

      - name: Debug files
        run: ls -R

      - name: Commit & push generated file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
